/*
 *   This file was AUTO-GENERATED by pypgmopts.
 *
 *   https://github.com/johndoe31415/pypgmopts
 *
 *   Do not edit it by hand, your changes will be overwritten.
 *
 *   Generated at: 2020-07-11 17:33:03
 */

#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <unistd.h>
#include <getopt.h>
#include <stdarg.h>
#include <string.h>
#include "argparse.h"

static enum argparse_option_t last_parsed_option;
static char last_error_message[256];
static const char *option_texts[] = {
	[ARG_RANDOM_BTLE_ADDRESS] = "-r / --random-btle-address",
	[ARG_USER] = "-u / --user",
	[ARG_CHOWN] = "-c / --chown",
	[ARG_VERBOSE] = "-v / --verbose",
	[ARG_DESTINATION_ADDRESS] = "destination_address",
	[ARG_UNIX_SOCKET] = "unix_socket",
};

enum argparse_option_internal_t {
	ARG_RANDOM_BTLE_ADDRESS_SHORT = 'r',
	ARG_USER_SHORT = 'u',
	ARG_CHOWN_SHORT = 'c',
	ARG_VERBOSE_SHORT = 'v',
	ARG_RANDOM_BTLE_ADDRESS_LONG = 1000,
	ARG_USER_LONG = 1001,
	ARG_CHOWN_LONG = 1002,
	ARG_VERBOSE_LONG = 1003,
	ARG_DESTINATION_ADDRESS_LONG = 1004,
	ARG_UNIX_SOCKET_LONG = 1005,
};

static void errmsg_callback(const char *errmsg, ...) {
	va_list ap;
	va_start(ap, errmsg);
	vsnprintf(last_error_message, sizeof(last_error_message), errmsg, ap);
	va_end(ap);
}

static void errmsg_option_callback(enum argparse_option_t error_option, const char *errmsg, ...) {
	last_parsed_option = error_option;

	va_list ap;
	va_start(ap, errmsg);
	vsnprintf(last_error_message, sizeof(last_error_message), errmsg, ap);
	va_end(ap);
}

bool argparse_parse(int argc, char **argv, argparse_callback_t argument_callback, argparse_plausibilization_callback_t plausibilization_callback) {
	last_parsed_option = ARGPARSE_NO_OPTION;
	const char *short_options = "ru:c:v";
	struct option long_options[] = {
		{ "random-btle-address",              no_argument, 0, ARG_RANDOM_BTLE_ADDRESS_LONG },
		{ "user",                             required_argument, 0, ARG_USER_LONG },
		{ "chown",                            required_argument, 0, ARG_CHOWN_LONG },
		{ "verbose",                          no_argument, 0, ARG_VERBOSE_LONG },
		{ "destination_address",              required_argument, 0, ARG_DESTINATION_ADDRESS_LONG },
		{ "unix_socket",                      required_argument, 0, ARG_UNIX_SOCKET_LONG },
		{ 0 }
	};

	while (true) {
		int optval = getopt_long(argc, argv, short_options, long_options, NULL);
		if (optval == -1) {
			break;
		}
		last_error_message[0] = 0;
		enum argparse_option_internal_t arg = (enum argparse_option_internal_t)optval;
		switch (arg) {
			case ARG_RANDOM_BTLE_ADDRESS_SHORT:
			case ARG_RANDOM_BTLE_ADDRESS_LONG:
				last_parsed_option = ARG_RANDOM_BTLE_ADDRESS;
				if (!argument_callback(ARG_RANDOM_BTLE_ADDRESS, optarg, errmsg_callback)) {
					return false;
				}
				break;

			case ARG_USER_SHORT:
			case ARG_USER_LONG:
				last_parsed_option = ARG_USER;
				if (!argument_callback(ARG_USER, optarg, errmsg_callback)) {
					return false;
				}
				break;

			case ARG_CHOWN_SHORT:
			case ARG_CHOWN_LONG:
				last_parsed_option = ARG_CHOWN;
				if (!argument_callback(ARG_CHOWN, optarg, errmsg_callback)) {
					return false;
				}
				break;

			case ARG_VERBOSE_SHORT:
			case ARG_VERBOSE_LONG:
				last_parsed_option = ARG_VERBOSE;
				if (!argument_callback(ARG_VERBOSE, optarg, errmsg_callback)) {
					return false;
				}
				break;

			default:
				last_parsed_option = ARGPARSE_NO_OPTION;
				errmsg_callback("unrecognized option supplied");
				return false;
		}
	}

	const int positional_argument_cnt = argc - optind;
	last_parsed_option = ARGPARSE_POSITIONAL_ARG;
	if (positional_argument_cnt != 2) {
		errmsg_callback("expected exactly 2 positional arguments, but %d given.", positional_argument_cnt);
		return false;
	}

	int positional_index = optind;
	last_parsed_option = ARG_DESTINATION_ADDRESS;
	if (!argument_callback(ARG_DESTINATION_ADDRESS, argv[positional_index++], errmsg_callback)) {
		return false;
	}
	last_parsed_option = ARG_UNIX_SOCKET;
	if (!argument_callback(ARG_UNIX_SOCKET, argv[positional_index++], errmsg_callback)) {
		return false;
	}

	if (plausibilization_callback) {
		if (!plausibilization_callback(errmsg_option_callback)) {
			return false;
		}
	}
	return true;
}

void argparse_show_syntax(void) {
	fprintf(stderr, "usage: btlehrservice [-r] [-u username] [-c oct_permissions] [-v]\n");
	fprintf(stderr, "                     dest_mac_address socket\n");
	fprintf(stderr, "\n");
	fprintf(stderr, "Bluetooth Low Energy Heart Rate service.\n");
	fprintf(stderr, "\n");
	fprintf(stderr, "positional arguments:\n");
	fprintf(stderr, "  dest_mac_address      BTLE MAC address of the device that the btlehrservice\n");
	fprintf(stderr, "                        should try to connect to.\n");
	fprintf(stderr, "  socket                UNIX socket that the btlehrservice listens on.\n");
	fprintf(stderr, "\n");
	fprintf(stderr, "optional arguments:\n");
	fprintf(stderr, "  -r, --random-btle-address\n");
	fprintf(stderr, "                        Use a random BTLE address. Some heartrate monitors\n");
	fprintf(stderr, "                        (e.g., Polar H9) seem to require this.\n");
	fprintf(stderr, "  -u username, --user username\n");
	fprintf(stderr, "                        Change the username of the unix_socket to this user\n");
	fprintf(stderr, "                        after it has been bound.\n");
	fprintf(stderr, "  -c oct_permissions, --chown oct_permissions\n");
	fprintf(stderr, "                        Change permissions of the unix_socket to this octal\n");
	fprintf(stderr, "                        permission value after it has been bound.\n");
	fprintf(stderr, "  -v, --verbose         Increase verbosity. Can be specified multiple times.\n");
}

void argparse_parse_or_quit(int argc, char **argv, argparse_callback_t argument_callback, argparse_plausibilization_callback_t plausibilization_callback) {
	if (!argparse_parse(argc, argv, argument_callback, plausibilization_callback)) {
		if (last_parsed_option > ARGPARSE_POSITIONAL_ARG) {
			if (last_error_message[0]) {
				fprintf(stderr, "btlehrservice: error parsing argument %s -- %s\n", option_texts[last_parsed_option], last_error_message);
			} else {
				fprintf(stderr, "btlehrservice: error parsing argument %s -- no details available\n", option_texts[last_parsed_option]);
			}
		} else if (last_parsed_option == ARGPARSE_POSITIONAL_ARG) {
			fprintf(stderr, "btlehrservice: error parsing optional arguments -- %s\n", last_error_message);
		}
		argparse_show_syntax();
		exit(EXIT_FAILURE);
	}
}

#ifdef __ARGPARSE_MAIN__
/*   gcc -D __ARGPARSE_MAIN__ -O2 -Wall -o argparse argparse.c
*/

static const char *option_enum_to_str(enum argparse_option_t option) {
	switch (option) {
		case ARG_RANDOM_BTLE_ADDRESS: return "ARG_RANDOM_BTLE_ADDRESS";
		case ARG_USER: return "ARG_USER";
		case ARG_CHOWN: return "ARG_CHOWN";
		case ARG_VERBOSE: return "ARG_VERBOSE";
		case ARG_DESTINATION_ADDRESS: return "ARG_DESTINATION_ADDRESS";
		case ARG_UNIX_SOCKET: return "ARG_UNIX_SOCKET";
	}
	return "UNKNOWN";
}

bool arg_print_callback(enum argparse_option_t option, const char *value, argparse_errmsg_callback_t errmsg_callback) {
	fprintf(stderr, "%s = \"%s\"\n", option_enum_to_str(option), value);
	return true;
}

int main(int argc, char **argv) {
	argparse_parse_or_quit(argc, argv, arg_print_callback, NULL);
	return 0;
}
#endif
