/*
 *   This file was AUTO-GENERATED by pypgmopts.
 *
 *   https://github.com/johndoe31415/pypgmopts
 *
 *   Do not edit it by hand, your changes will be overwritten.
 *
 *   Generated at: 2019-09-29 10:03:18
 */

#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <unistd.h>
#include <getopt.h>
#include <stdarg.h>
#include <string.h>
#include "argparse.h"

static enum argparse_option_t last_parsed_option;
static char last_error_message[256];
static const char *option_texts[] = {
	[ARG_DESTINATION_ADDRESS] = "destination_address",
	[ARG_UNIX_SOCKET] = "unix_socket",
};

enum argparse_option_internal_t {
	ARG_DESTINATION_ADDRESS_LONG = 1000,
	ARG_UNIX_SOCKET_LONG = 1001,
};

static void errmsg_callback(const char *errmsg, ...) {
	va_list ap;
	va_start(ap, errmsg);
	vsnprintf(last_error_message, sizeof(last_error_message), errmsg, ap);
	va_end(ap);
}

static void errmsg_option_callback(enum argparse_option_t error_option, const char *errmsg, ...) {
	last_parsed_option = error_option;

	va_list ap;
	va_start(ap, errmsg);
	vsnprintf(last_error_message, sizeof(last_error_message), errmsg, ap);
	va_end(ap);
}

bool argparse_parse(int argc, char **argv, argparse_callback_t argument_callback, argparse_plausibilization_callback_t plausibilization_callback) {
	last_parsed_option = ARGPARSE_NO_OPTION;
	const char *short_options = "";
	struct option long_options[] = {
		{ "destination_address",              required_argument, 0, ARG_DESTINATION_ADDRESS_LONG },
		{ "unix_socket",                      required_argument, 0, ARG_UNIX_SOCKET_LONG },
		{ 0 }
	};

	while (true) {
		int optval = getopt_long(argc, argv, short_options, long_options, NULL);
		if (optval == -1) {
			break;
		}
		last_error_message[0] = 0;
		enum argparse_option_internal_t arg = (enum argparse_option_internal_t)optval;
		switch (arg) {
			default:
				last_parsed_option = ARGPARSE_NO_OPTION;
				errmsg_callback("unrecognized option supplied");
				return false;
		}
	}

	const int positional_argument_cnt = argc - optind;
	if (positional_argument_cnt < 2) {
		errmsg_callback("expected a minimum of 2 positional arguments, %d given.", positional_argument_cnt);
		return false;
	}
	if (positional_argument_cnt > 2) {
		errmsg_callback("expected a maximum of 2 positional arguments, %d given.", positional_argument_cnt);
		return false;
	}

	int positional_index = optind;
	last_parsed_option = ARG_DESTINATION_ADDRESS;
	if (!argument_callback(ARG_DESTINATION_ADDRESS, argv[positional_index++], errmsg_callback)) {
		return false;
	}
	last_parsed_option = ARG_UNIX_SOCKET;
	if (!argument_callback(ARG_UNIX_SOCKET, argv[positional_index++], errmsg_callback)) {
		return false;
	}

	if (plausibilization_callback) {
		if (!plausibilization_callback(errmsg_option_callback)) {
			return false;
		}
	}
	return true;
}

void argparse_show_syntax(void) {
	fprintf(stderr, "usage: btlehrservice dest_mac_address socket\n");
	fprintf(stderr, "\n");
	fprintf(stderr, "Bluetooth Low Energy Heart Rate service.\n");
	fprintf(stderr, "\n");
	fprintf(stderr, "positional arguments:\n");
	fprintf(stderr, "  dest_mac_address  BTLE MAC address of the device that the btlehrservice\n");
	fprintf(stderr, "                    should try to connect to.\n");
	fprintf(stderr, "  socket            UNIX socket that the btlehrservice listens on.\n");
}

void argparse_parse_or_quit(int argc, char **argv, argparse_callback_t argument_callback, argparse_plausibilization_callback_t plausibilization_callback) {
	if (!argparse_parse(argc, argv, argument_callback, plausibilization_callback)) {
		if (last_parsed_option != ARGPARSE_NO_OPTION) {
			if (last_error_message[0]) {
				fprintf(stderr, "%s: error parsing argument %s -- %s\n", argv[0], option_texts[last_parsed_option], last_error_message);
			} else {
				fprintf(stderr, "%s: error parsing argument %s -- no details available\n", argv[0], option_texts[last_parsed_option]);
			}
		}
		argparse_show_syntax();
		exit(EXIT_FAILURE);
	}
}

bool argparse_argument_one_of_choices(const char *value, const char **value_list) {
	while (*value_list) {
		if (!strcmp(*value_list, value)) {
			return true;
		}
		value_list++;
	}
	errmsg_callback("'%s' is not a valid choice for this option", value);
	return false;
}

#ifdef __ARGPARSE_MAIN__
/*   gcc -D __ARGPARSE_MAIN__ -O2 -Wall -o argparse argparse.c
*/

static const char *option_enum_to_str(enum argparse_option_t option) {
	switch (option) {
		case ARG_DESTINATION_ADDRESS: return "ARG_DESTINATION_ADDRESS";
		case ARG_UNIX_SOCKET: return "ARG_UNIX_SOCKET";
	}
	return "UNKNOWN";
}

bool arg_print_callback(enum argparse_option_t option, const char *value, argparse_errmsg_callback_t errmsg_callback) {
	fprintf(stderr, "%s = \"%s\"\n", option_enum_to_str(option), value);
	return true;
}

int main(int argc, char **argv) {
	argparse_parse_or_quit(argc, argv, arg_print_callback, NULL);
	return 0;
}
#endif
