#!/usr/bin/python3
#	btlehrservice - Bluetooth-Low-Energy heart rate service
#	Copyright (C) 2020-2020 Johannes Bauer
#
#	This file is part of btlehrservice.
#
#	btlehrservice is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	btlehrservice is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with btlehrservice; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
import json
import socket
from FriendlyArgumentParser import FriendlyArgumentParser
from Recorder import Recorder

parser = FriendlyArgumentParser(description = "Record heartrate values that were captured.")
parser.add_argument("-c", "--config", metavar = "filename", type = str, default = "config.json", help = "Specifies configuration file to use. Defaults to %(default)s.")
parser.add_argument("-v", "--verbose", action = "count", default = 0, help = "Increases verbosity. Can be specified multiple times to increase.")
args = parser.parse_args(sys.argv[1:])

recorder = Recorder(args)
recorder.run()
